AUTH_HOST: http://localhost
AUTH_PORT: 8080
AUTH_REALM: my-realm
AUTH_CLIENT_ID: music-player
AUTH_CLIENT_SECRET: JB1A4KeShvFMTvPN5kUFZh1JAkXRiOTZ
AUTH_ADMIN_USERNAME: realmadmin
AUTH_ADMIN_PASSWORD: realmadmin
AUTH_TOKEN_ENDPOINT: ${AUTH_HOST}:${AUTH_PORT}/realms/${AUTH_REALM}/protocol/openid-connect/token

S3_INTERNAL_HOST: http://localhost
S3_INTERNAL_PORT: 9000
S3_EXTERNAL_HOST: http://localhost
S3_EXTERNAL_PORT: 9000
S3_AUDIO_BUCKET: mp-audio
S3_IMAGE_BUCKET: mp-image
S3_ACCESS_KEY: c03mrjtvd2X89u8n
S3_SECRET_KEY: Cu6ScvC93L31UYzBheq5jJoZjVF1I5eV